name: CI/CD
on:
  push:
    branches:
      - main
    paths-ignore:
      - 'chat-app-helm'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Print working directory
        run: pwd

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push frontend Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./frontend  # Set context to the frontend directory
          file: ./frontend/Dockerfile  # Path to Dockerfile inside the frontend directory
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/chat-app-frontend:${{ github.run_id }}

      - name: Build and Push backend Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./  # Use the root of the repo as context for backend
          file: ./backend/Dockerfile  # Path to Dockerfile inside the backend directory
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/chat-app-backend:${{ github.run_id }}
