name: CI/CD
on:
  push:
    branches:
    - main
    paths-ignore:
      - 'chat-app-helm'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
     
      - 
        name: Build and Push action backend
        uses: docker/build-push-action@v6
        with:
          context: ./frontend
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/chat-app:${{github.run_id}}