name: CI/CD
on:
  push:
    branches:
    - main
    paths-ignore:
      - 'chat-app-helm'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # Login to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Build the backend Docker image using the Docker CLI
      - name: Build and Push action backend (CLI)
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/chat-app-backend:${{ github.run_id }} -f ./backend/Dockerfile ./  # Use the root as context
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/chat-app-backend:${{ github.run_id }}

      # Build the frontend Docker image using the Docker CLI (if needed)
      - name: Build and Push action frontend (CLI)
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/chat-app-frontend:${{ github.run_id }} -f ./frontend/Dockerfile ./  # Use the root as context
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/chat-app-frontend:${{ github.run_id }}
