name: CI/CD
on:
  push:
    branches:
    - main
    paths-ignore:
      - 'chat-app-helm'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Print working directory
        run: pwd  # This will print the current working directory in the logs

      - name: Build and Push frontend Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./  # Root of the repo as context
          file: ./frontend/Dockerfile  # Path to Dockerfile inside 'backend' folder
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/chat-app-backend:${{ github.run_id }}
