name: CI/CD
on:
  push:
    branches:
    - main
    paths-ignore:
      - 'chat-app-helm'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      # Step to login to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Step to build and push backend Docker image
      - name: Build and Push action backend
        uses: docker/build-push-action@v6
        with:
          context: ./  # Use the root of the repository as the build context
          file: ./backend/Dockerfile  # Dockerfile is inside the 'backend' directory
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/chat-app-backend:${{ github.run_id }}
